### ISSUE TITLE
Hexagon support

### ISSUE THREAD

**Issue by soft-circles** [Droggelbecher/bevy-fast-tilemap#12]
Are there plans to support hexagon tilemaps?

**Comment by Droggelbecher** [comment]
Currently, no. As a 1 man army, I can currently pretty much only build what I need, but I am open to contributions and it should certainly be possible to do from a technical standpoint.

**Comment by Droggelbecher** [comment]
Some pointers in case someone wants to look into this in the future:
Currently we project 2d<->2d coordinates which allows conversion between map/tile coordinates and world coordinates for eg isometric where you have a diamond-like shape of tiles.
For hex your tiles need 6 sides rather than 4 so your tile coordinates would have to become 3d (even though 1 dimension is redundant) so you get all the edges you need.
Also check out redblobgames for lots of info on hex tiles including how to work with those 3d coordinates.

Closing this now as for me its currently out of scope, but contributions on this are welcome and I may pick it up my self some later point in the future.
