### ISSUE TITLE
adding a custom shader

### ISSUE THREAD

**Issue by sum-catnip** [Droggelbecher/bevy-fast-tilemap#16]
hi,

is it possible to add some shader post processing to the tilemap or maybe use a custom implementation of [tilemap_shader.wgsl](https://github.com/Droggelbecher/bevy-fast-tilemap/blob/master/assets/tilemap_shader.wgsl)?

**Comment by Droggelbecher** [comment]
Hey @sum-catnip , I'm currently not aware of a way to combine multiple shader implementations in bevy, but that might just be my limited knowledge. Since the shader code is a string it could theoretically be extended, but in either case you would have to be aware of its internal workings so if you want something really custom you might be better off forking your own.

What exactly are you going for? Maybe we can find some other way to achieve that?

**Comment by sum-catnip** [comment]
Thanks for the reply! I came to the same conclusion but i figured maybe i was misunderstanding something.

I was looking into this crate for use in a gamejam. I might just copy paste your code in for quick modification (with license and credit ofc) if thats okay :)

**Comment by Droggelbecher** [comment]
Ah yeah sure, feel free to do so. But good point I should choose and add a license :)
