### ISSUE TITLE
Feature Request: Tile Colors (background and foreground)

### ISSUE THREAD

**Issue by matthemsteger** [Droggelbecher/bevy-fast-tilemap#17]
You might have a bunch of tiles (a most obvious example is when your tiles are really cp-437 ascii in a roguelike) that you want to "tint". I see that you just added a feature for map attributes that sets a color, which it looks like applies more or less a color to the entire map? It would be nice to be able to apply colors to tiles independently.

I had a hand at a prototype by changing to store a struct in the storage buffer that contains the index and foreground and background colors. That *could* work .. but I also found it seemed to run things a bit slower. I am wondering what your thoughts are for including a feature like this in the library?

**Comment by Droggelbecher** [comment]
Maybe we can do a second storage buffer that stores a color for every tile, not sure thats faster than your solution (I guess depends a lot on the GPU as well). Right now we're reserving 32 bits for the tile type, and I doubt anybody has such a large tile atlas. If you have eg no more than 256 different types of tiles we could just use the remaining 3 bytes for color.

This I wouldn't wanna make the default though as some people (including me) might want to use more than 256. Maybe we could do something like have a ShaderDef that defines how many bytes are used for actual tile index and allow the user to insert some shader code that does something with the remaining bytes? That would however add some complexity and probably still need to hardcode the assumption that everything you need fits into 32 bits (otherwise it becomes even more complex).

Also not sure what you mean with background and foreground colors?

**Comment by matthemsteger** [comment]
A concrete use case would probably be prototyping/simple roguelike games. But I think it would be widely useful to color a tile dynamically (e.g. like a grass tile turning brown).

So for example this traditional cp-437 tileset:
![Md-curses-16x16](https://github.com/Droggelbecher/bevy-fast-tilemap/assets/1319046/db1558c1-7cdd-42cf-98f4-20596918ad00)

For example, a triangle might be tinted brown when looking at the global map. And then in the game world, a triangle might be an up ramp, and the color of the ramp depends on what kind of terrain it is.

In the tileset above, foreground is the white, background is the black. Though I suppose there is already a solution for background .. just have a layer under.

**Comment by Droggelbecher** [comment]
I actually couldn't resist to build something that could help with this :)

If you like, could you check out #19 and give me some feedback.
The custom_shader example should explain how to use it.
This opens up a way to use whatever extra bits you can spare in the 32 bits tile index to do whatever per-tile shenanigans you can express in WGSL. In the example it uses a single byte to tint some tiles red but should be easy enough to extend to indexing a color palette or whatever you like.

**Comment by Droggelbecher** [comment]
With 0.7.1 you can inject some custom shader code (examples included), that should make this easy to address, lemme know what you think.
