### ISSUE TITLE
interacting with sprites / tiles

### ISSUE THREAD

**Issue by Mergpijp** [Droggelbecher/bevy-fast-tilemap#34]
Hi,

I want to put an image that encompasses multiple tiles however now it highlights as single tile using your highlight example. What is a good approach for this?

**Comment by Droggelbecher** [comment]
I think in some way you would need code that understands for each of these tiles which other tiles it belongs to. You could either do this in the shader or on CPU. Since likely your game logic needs to know which tiles are affected anyway, I would think CPU side should be better.

That is: When you have figured out which tile the mouse hovered over, figure out which tiles should be highlighted together with this one. Theres a billion ways you could do this depending on your needs, for example you could have a hash map that maps each tile position to a vector of tiles that belong to it, or you could see by the tile type that its eg a "lower left" corner and then you can deduct from that which neighbors you need to check.

For highlighting multiple tiles in bevy-fast-tilemap, you can either a) reserve a bit in the tile index (as in https://github.com/Droggelbecher/bevy-fast-tilemap/blob/master/examples/custom_shader_code.rs#L68 ) or b) if you know eg no more than 4 tiles are ever highlighted at the same time, have 4 entries in your user data struct.

**Comment by Mergpijp** [comment]
Yes thank you I did the last option kind of the spritebundle has a component and I store those coordinates. And for another question I want a pop up window with clickable images what bevy plugin should I use?

**Comment by Droggelbecher** [comment]
For popup windows no idea sorry. Check out https://bevyengine.org/community/ for pointers to the broader bevy community, Im sure somebody there knows what you seek.
